name: bokeh_for_map
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - geopandas=0.7.0
  - bokeh=2.0.2
  - Shapely=1.7.0
  - GDAL=3.0.4
  - pytest=5.4.2
  - pytest-cov=2.8.1
  - jupyter=1.0.0