{% set name = "geo_bokeh" %}
{% set version = "0.5.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: ..

build:
  number: 1

requirements:
  build:
    - python
    - pip
    - geopandas
    - bokeh
  run:
    - geopandas
    - bokeh

about:
  home: https://github.com/amauryval/geo_bokeh
  license: MIT
  license_family: MIT
  summary: geo bokeh
  license_file: LICENSE
