{% set name = "easy_map_bokeh" %}
{% set version = "0.5.4" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: ..

build:
  number: 1

requirements:
  host:
    - python >=3.6
  build:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - geopandas >=0.8.0
    - bokeh >=2.0.1

about:
  home: https://github.com/amauryval/easy_map_bokeh
  license: MIT
  license_family: MIT
  summary: geo bokeh
  license_file: LICENSE
